title: "Matthews-Project-Vault"
tagline: "Ruby, Jekyll, HACKED"
description: "Project-site"
github_username: Matthew-a-smith
baseurl: "WilsonsTech.github.io"
url: "https://WilsonsTech.github.io"

plugins:
  - jekyll-paginate-v2  # Make sure this is at the top of the list
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag


header_pages:
  - home.md
  - index.md
  - about_me.md

permalink: articles/:year/:month/:title.html

# Pagination Settings
pagination:
  enabled: true
  per_page: 3
  limit: 0
  sort_field: 'date'
  sort_reverse: true

font-size: large









