title: "Matthews-Project-Vault"
tagline: "Personal Site for my articles and projects"
description: "This is my personal site, Please look at my articles or my about me page"
github_username: Matthew-a-smith
baseurl: "/home"
url: "http://localhost:4000/home/"

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed

highlighter: rouge

header_pages:
  - home.md
  - read-me.md
  - preview.md
  - article.md
      
#paginate: 4
#per_page: 4
#paginate_path: "/article/page/:num/"

# set the size of the text to 'large' or 'small', default is small
font-size: small